enableTrading: true
enablePaging: true

authenticateExchanges: true
backgroundRetryExchanges: false

maxOrderStaleness: PT2S
maxArbLength: 3
noArbsFoundSleep: PT0.3S

failedOrderFromExchangeToleranceInterval: PT1H
balanceVsFillsProfitEpsilonTolerance: 100e-8

exchangeInstantiationRetryInterval: PT10M
exchangeBalanceRefreshInterval: PT1M
exchangeWithdrawalFeeRefreshInterval: PT30M
exchangeMinimumTradeRestrictionRefreshInterval: PT30M

orderTimestampEpsilon: PT20S
initialOrderFillWaitTime: PT15S
initialOpenOrderWaitTime: PT2S
balanceChangeWaitTime: PT5S

arbitrageTrackerWaitTime: PT2H
arbitrageTrackerRefreshRate: PT50M

lowBalnceInitialNotificationInterval: PT10M
lowBalanceExponentialBackoff: 3
lowBalanceMaxNotificationInterval: P1D
lowBalanceNoActivityResetInterval: PT30M
minRatioForNotify: 0.2

whitelistedCurrencies:
- Bitcoin
- Ether
- Binance Coin
- United States Dollar
- Monero
- Basic Attention Token
- Golem
- ZRX
- PTOY
- ANT
- EDG
- CVC
- Augur
- Zcash
- Ether Classic
- GEO
- Litecoin
- Stellar
minConversionRatioWithWithdrawalFees: 1.0015
minConversionRatioWithoutWithdrawalFees: 1.0015

maxOrderBookSize: 50
orderBookPollingPort: 13377
receiverThreadCount: 10
exchangeReceiverBufferSize: 1024000
clientReadTimeout: PT6S

latencyMetricsSlidingTimeWindow: PT15M
latencyMetricsReportInterval: PT15M
legacyMetricsFrequency: 25

pollerReportsPerFile: 20
pollerWriteLogsInterval: PT2H
rateLimitExceededBackoff: PT60S
pollingExceptionBackoff: PT15S

transactionLogsWriteSize: 256000

krakenTier: 3

logToS3: true
logToConsole: false
debugLocalPriceUpdates: false